# Generated by Django 5.2.7 on 2026-08-20 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('PLACEMENT', 'Full-Time Placement')], default='INTERNSHIP', max_length=20)),
                ('job_role', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('required_skills', models.TextField(help_text='Comma-separated skills (e.g. Python, Django, React, SQL)')),
                ('location', models.CharField(max_length=150)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ON_SITE', 'On-Site'), ('HYBRID', 'Hybrid')], default='ON_SITE', max_length=20)),
                ('stipend', models.CharField(blank=True, default='', help_text='e.g. ₹25,000 / month (or Unpaid / Performance based)', max_length=100)),
                ('salary', models.CharField(blank=True, default='', help_text='e.g. ₹6 - 10 LPA', max_length=100)),
                ('duration', models.CharField(blank=True, default='', help_text='e.g. 3 Months, 6 Months, Permanent', max_length=100)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum CGPA cutoff (e.g. 7.00, 0 for no cutoff)', max_digits=4)),
                ('eligible_degree', models.CharField(default='All Degrees', help_text='e.g. B.Tech, M.Tech, BCA, MCA, B.Sc or All Degrees', max_length=255)),
                ('eligible_department', models.CharField(default='All Departments', help_text='e.g. Computer Science, Information Technology, ECE or All Departments', max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Target graduating batch year (e.g. 2025, 2026, or blank for any)', null=True)),
                ('application_deadline', models.DateField()),
                ('openings_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='recruiters.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='opportunities.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Opportunity',
                'verbose_name_plural': 'Saved Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'opportunity_type'], name='opportuniti_status_75139c_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['location', 'work_mode'], name='opportuniti_locatio_885deb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['application_deadline'], name='opportuniti_applica_37b87c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedopportunity',
            unique_together={('student', 'opportunity')},
        ),
    ]
